#!/usr/bin/env python3
# BRIEF: Print the absolute path for a given file or directory
# USAGE: abspath FILE

import os.path
import sys

if len(sys.argv) > 1 and os.path.exists(sys.argv[1]):
    print(os.path.abspath(sys.argv[1]))
else:
    sys.exit(1)
