#!/bin/bash
##############################################################################
#
# NAME:         apt-get
#
# DESCRIPTION:  A wrapper for apt-get that takes coffee as an extra command
#               that simply locks the screen in Gnome.
#
#               This is a joke script, in case it was not obvious :)
#
#               At work, the security policy forces me to lock my screen
#               whenever I am away from the computer, e.g. when I am getting
#               some coffee.
#
# USAGE:        apt-get coffee
#
# DEPENDENCIES: 
#               * gnome-screensaver-command
#               * /usr/bin/apt-get
#
##############################################################################
#

[[ 'coffee' = $1 ]] && which gnome-screensaver-command > /dev/null &&
    exec gnome-screensaver-command --lock

/usr/bin/apt-get "$@"
