#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "click",
#     "pyyaml",
# ]
# ///
# BRIEF: Convert JSON files to YAML format
# USAGE: json-to-yaml [input_file] [output_file]
# USAGE:   Defaults to stdin/stdout if files not specified

import click
import yaml

@click.command(context_settings=dict(help_option_names=["-h", "--help"]))
@click.argument("input_file", type=click.File("r"), default="-")
@click.argument("output_file", type=click.File("w"), default="-")
def main(input_file: click.File, output_file: click.File) -> None:
    """
    Convert a JSON file to a YAML file.

    json-to-yaml <input_file> <output_file>

    - input_file: The input JSON file. If - or omitted, read from stdin.
    - output_file: The output YAML file. If - or omitted, write to stdout.
    """
    yaml.dump(yaml.safe_load(input_file), output_file)


if __name__ == "__main__":
    main()
