#!/bin/bash
##############################################################################
#
# NAME:         lsrepos
#
# DESCRIPTION:  List the subdirectories under the current directory that are
#               version controlled and specify which version control system
#               they use.
#               If extra arguments are given, they will be trated as
#               directories and will be checked for version control system
#               themselves.
#
# USAGE:        lsrepos [DIRECTORY [DIRECTORY ...]]
#
# DEPENDENCIES: None  
#
##############################################################################
#

detect_repo()
{
    for file in "$@"
    do
        if [[ $file != '.' ]] && [[ $file != '..' ]]
        then
            if   [[ -d $file/.git ]]; then # Git repository
                echo "GIT $file"
            elif [[ -d $file/.svn ]]; then # Subversion repository
                echo "SVN $file"
            elif [[ -d $file/.hg ]]; then  # Mercurial repository
                echo "HG  $file"
            fi
        fi
    done
}


if [[ $# < 1 ]]; then
    detect_repo *
else
    detect_repo "$@"
fi

