#!/usr/bin/env bash

set -e

function die()
{
    echo "$*" 1>&2
    exit 1
}

function usagedie()
{
    echo "USAGE: new <template> <file>"
    echo "       new -l"
    die $@
}

function check_env()
{
    [[ -n $SOURCE_TEMPLATES ]] || die "Source templates dir not set. Use SOURCE_TEMPLATES"
    [[ -d $SOURCE_TEMPLATES ]] || die "Source templates dir not found"
}

function check_args()
{
    [[ -n $1 ]] || usagedie "No source template provided"
    [[ -n $2 ]] || usagedie "No destination file name provided"
}

function main()
{
    check_env

    if [[ $1 == '--complete' ]] || [[ $1 == '-l' ]]; then
        ( builtin cd $SOURCE_TEMPLATES; ls -1 )
        exit 0
    fi

    check_args "$@"

    local source_template="$SOURCE_TEMPLATES/$1" 

    [[ -f $source_template ]] || die "Specified source template not found"

    command cp -r "$source_template" "$2"
}

main "$@"
