#!/bin/bash
##############################################################################
#
# NAME:         pid
#
# DESCRIPTION:  Show all the processes owned by me that match certain name
#               criteria.
#
# USAGE:        pid [-n] [PATTERN]
#               -n      Does not show the ps header
#               PATTERN A pattern to match the process names. If no pattern
#                       is specified, all user's processes are shown.
#
# DEPENDENCIES: None  
#
##############################################################################
#

#-----------------------------------------------------------------------------
usage()
{
    sed -e 's/^    //' <<'USAGE'
    Usage:

    pid [-n] [PATTERN]

      -n      Does not show the ps header
      PATTERN A pattern to match the process names. If no pattern
              is specified, all user's processes are shown.

USAGE
    exit $1
}
#-----------------------------------------------------------------------------


# Only asking for help
[[ $1 = '-h' ]] && usage 0

# Headers or not?
if [[ $1 = -n ]]; then
    showheader=0
    shift
else
    showheader=1
fi


# The meat!
ps aux | awk \
            -v user="$USER" \
            -v proc="$1" \
            -v showheader="$showheader" \
            -v shell_pid="$$" \
            '
    BEGIN {
        username_pattern="^" user;
    }
    {
        if (showheader == 1 && NR == 1)
        {
            header = $0;
        }
        awk_pid =  PROCINFO["pid"];
        if (($0 ~ username_pattern) && ($0 ~ proc) && 
            ($2 != awk_pid) && ($2 != shell_pid) )
        {
            if (showheader == 1)
            {
                showheader = 0;
                print header;
            }
            print $0;
        }
    }'

# vim: fdm=marker :
