#!/usr/bin/env bash
##############################################################################
#
# NAME:         purehome
#
# DESCRIPTION:  Provides a very visible warning when the contents directly
#               under the current user's home directory deviate from a set of
#               expected contents. 
#
# USAGE:        purehome
#
# DEPENDENCIES: figlet cowsay
#
##############################################################################
#

expected_contents='
backup
comms
devel
doc
media
other'

function check_home_purity()
{
   local diff=$( diff --suppress-common-lines -wB \
      <( ls ~ | sort) \
      <( echo -e "$expected_contents") \
      )
   [[ -z $diff ]] && return 0
   local rubbish=$(echo "$diff" | grep '^<' | cut -c 3-)
   local missing=$(echo "$diff" | grep '^>' | cut -c 3-)
   if [[ -n "${rubbish}${missing}" ]]; then
       echo "Home is WRONG" | figlet -f small
   fi
   if [[ -n $missing ]]; then
       echo "Missing directories:"
       echo "$missing" | sed 's/^/ * /'
   fi
   if [[ -n $rubbish ]]; then
       echo "Superfluous contents:"
       echo "$rubbish" | sed 's/^/ * /'
   fi
}


message="$(check_home_purity "$@")"
if [[ -n $message ]]; then
    echo "$message" | cowsay -n
fi
