#!/usr/bin/env python3
# -*- coding: utf-8 -*-

##############################################################################
#
# NAME:         relpath 
#
# DESCRIPTION:  Prints a given path relative to another directory
#
# USAGE:        relpath FILE [DIR]
#
# DEPENDENCIES: None
#
##############################################################################
#

__description__ = 'Prints a given path relative to another directory'

# ---------------------------------------------------------------------------
# Standard imports:
import sys
import argparse
import os
# ---------------------------------------------------------------------------



def parse_args(argv):
    """ Parse and validate command line arguments """
    parser = argparse.ArgumentParser(description=__description__)
    parser.add_argument('path')
    parser.add_argument('base', nargs='?', default='.')
    args = parser.parse_args(argv[1:])
    return args


def main(argv=None):
    """ Run this program """
    if argv is None:
        argv = [__name__]
    args = parse_args(argv)
    try:
        print(os.path.relpath(args.path, args.base))

    except KeyboardInterrupt:
        sys.exit(-1)

if __name__ == '__main__':
    sys.exit(main(sys.argv) or 0)
