#!/usr/bin/env bash

# Get PEM formatted certificate chain for a particular SSL connection
set -e

host="$1"
port="${2:-443}"
output="$3"

usage()
{
    echo "Usage: $(basename "$0") <host> [<port>] [<output-file>]">&2
    exit 1
}

[[ $# -lt 1 || $# -gt 3 ]] && usage

[[ -n $output || $output == '-' ]] && exec >"$output"

echo Q |
    openssl s_client -showcerts -connect "$host:$port" -prexit 2>/dev/null |
    sed -n -e '/BEGIN\ CERTIFICATE/,/END\ CERTIFICATE/ p'
