#!/usr/bin/env bash
# BRIEF: Interactively select a chezmoi-managed file with fzf
# DESC: Shows managed files with their destination paths, supports preview with bat
# DESC: and opening in editor with Ctrl-O. Translates chezmoi source paths to their
# DESC: final destination paths by removing prefixes and extensions.
# DEPS: chezmoi, fzf, fd, bat

chezmoi_pick_file() {
    local source_path
    local query_args=()
    if [[ -n $1 ]]; then
        query_args=(--query "$@")
    fi
    source_path="$(chezmoi source-path)"
    # shellcheck disable=SC2016 # Allow $EDITOR in single quotes
    (
        fd --base-directory="$source_path" --type f --type l --hidden |
            while read -r file; do
                destination_path=$(chezmoi target-path "$source_path/$file")
                printf "%s\t%s\n" "$destination_path" "$file"
            done
    ) |
        fzf \
            --delimiter="\t" \
            --accept-nth=2 \
            --with-nth=1 \
            --exit-0 \
            --preview 'bat --style=full --color=always '"$source_path/{2}" \
            --bind 'ctrl-o:execute:$EDITOR '"$source_path/{2}" \
            "${query_args[@]}"
}

chezmoi_pick_file "$@"
