#!/usr/bin/env bash
# BRIEF: Show current git committer and author identity
# USAGE: git-identity [--porcelain|--json]
# DEPS: git jq sed

function get_identity()
{
    local label=$1
    git var -l | grep "GIT_${label}_IDENT" | sed -E 's/^[^=]+=([^>]+>).*$/\1/'
}

committer=$(get_identity COMMITTER)
author=$(get_identity AUTHOR)

case $1 in
    --porcelain)
        echo "git_commiter=\"$committer\""
        echo "git_author=\"$author\""
        exit 0
        ;;
    --json)
        jq -n --arg committer "$committer" --arg author "$author" '{committer: $committer, author: $author}'
        exit 0
        ;;
    *)
        ;;
esac

if [[ $committer == "$author" ]]
then
    echo "Committer and Author: $committer"
else
    echo "Committer: $committer"
    echo "Author: $author"
fi

