#!/bin/bash
# BRIEF: Show lines exceeding a given character length
# DESC: Scans files for lines longer than the specified length and outputs
# DESC: the filename, line number, and contents in a format compatible with
# DESC: Vim's quickfix mode.
# USAGE: longlines [-h] [-l MAX_LENGTH] FILE [FILE2 ...]
# USAGE:   -h              Show usage
# USAGE:   -l MAX_LENGTH   Maximum allowed line length (default: 80)
# DEPS: awk sed

DEFAULT_LINE_LENGTH=80

#-----------------------------------------------------------------------------
usage()
{
    sed -e 's/^    //' <<'USAGE'
    Usage:

    longlines [-l MAX_LENGTH] FILE [ FILE2 [FILE 3...]]

      -h                Show usage
      -l MAX_LENGTH     Maximum allowed line length

USAGE
    exit $1
}
#-----------------------------------------------------------------------------

# Only asking for help
[[ $1 = '-h' ]] && usage 0

# How long the lines can be
if [[ $1 = '-l' ]]
then
    linelen=$2
    shift
    shift
else
    linelen=$DEFAULT_LINE_LENGTH
fi

# Still need at least a file to check
[[ $# = 0 ]] && usage 1

awk -v linelen=$linelen '
{
    if (length() > linelen)
        printf("%s:%d:%s\n", FILENAME, NR, $0);
}' "$@"
